// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MinimalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105185059_AgregarConexiones")]
    partial class AgregarConexiones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Biblioteca.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Autorizada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DerivadaAProfesionalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Practica")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Biblioteca.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Biblioteca.Profesional", b =>
                {
                    b.Property<int>("IdProfesional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProfesional"));

                    b.Property<int?>("EspecialidadIdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int?>("SedeIdSede")
                        .HasColumnType("int");

                    b.HasKey("IdProfesional");

                    b.HasIndex("EspecialidadIdEspecialidad");

                    b.HasIndex("SedeIdSede");

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("Biblioteca.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("IdRol");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("Biblioteca.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("IdSede");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("Biblioteca.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<int>("EspecialidadIdEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfesional")
                        .HasColumnType("int");

                    b.Property<int>("IdSede")
                        .HasColumnType("int");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("ProfesionalIdProfesional")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(8)");

                    b.Property<int>("SedeIdSede")
                        .HasColumnType("int");

                    b.HasKey("IdTurno");

                    b.HasIndex("EspecialidadIdEspecialidad");

                    b.HasIndex("PacienteIdPaciente");

                    b.HasIndex("ProfesionalIdProfesional");

                    b.HasIndex("SedeIdSede");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Biblioteca.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Biblioteca.Orden", b =>
                {
                    b.HasOne("Biblioteca.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Biblioteca.Profesional", b =>
                {
                    b.HasOne("Biblioteca.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadIdEspecialidad");

                    b.HasOne("Biblioteca.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeIdSede");

                    b.Navigation("Especialidad");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Biblioteca.Turno", b =>
                {
                    b.HasOne("Biblioteca.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadIdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalIdProfesional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeIdSede")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Biblioteca.Usuario", b =>
                {
                    b.HasOne("Biblioteca.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Biblioteca.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
